language: scala
scala:
   - 2.11.11
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/81e81b14eb7b50a2ee95
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always